trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  isDevelopBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  isReleaseBranch: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')]
  testWorkingDirectory: 'srbetancBBDDSQl.Test'
  testProjectFilePath: 'srbetancBBDDSQl.Test/srbetancBBDDSQl.Test.csproj'
  sonarProjectKey: 'ws-wsserviciobase-netcore'
  project: 'srbetancBBDDSQl.API'
  repositoryImageName: 'bp/dominio/ws-srbetancbbddsql-netcore'
  openshiftImageStream: srbetancbbddsql
  openshiftNamespace: dominio


resources:
 repositories:
   - repository: NetcoreTemplate
     type: git
     name: BP-DevOps-Infrastructure/common-pipeline-template-netcore
     ref: refs/heads/masterv2

extends:
  template: init.yml@NetcoreTemplate
  parameters:
    netCoreVersion: '6.0.201' 
    coverletVersion: '3.1.2' 
    RPA_SUBSCRIPTION_SERVICE_CONNECTION: 'SREDevSecOps (rg-confidential)-BP-Arquetipos'